### ISSUE TITLE
Ender IO's Item Conduit (1.10.2-3.1.193)+External Distributor (2-2.2.0.86) =Crash

### ISSUE THREAD

**Issue by 88j381ilrprgb83fpp4d** [TechReborn/StevesCarts#168]
↓Crash Report
```
Description: Unexpected error

java.lang.ClassCastException: vswe.stevescarts.blocks.tileentities.TileEntityDetector cannot be cast to crazypants.enderio.conduit.IConduitBundle
	at crazypants.enderio.conduit.AbstractItemConduit.func_180614_a(AbstractItemConduit.java:87)
	at net.minecraft.item.ItemStack.func_179546_a(ItemStack.java:146)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:454)
	at PlayerControllerOF.func_187099_a(PlayerControllerOF.java:97)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1518)
	at net.minecraft.client.Minecraft.redirect$onRightClickMouse$zzg000(Minecraft.java:146)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2184)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1961)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1749)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at crazypants.enderio.conduit.AbstractItemConduit.func_180614_a(AbstractItemConduit.java:87)
	at net.minecraft.item.ItemStack.func_179546_a(ItemStack.java:146)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:454)
	at PlayerControllerOF.func_187099_a(PlayerControllerOF.java:97)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1518)
	at net.minecraft.client.Minecraft.redirect$onRightClickMouse$zzg000(Minecraft.java:146)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2184)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1961)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['TakahiroKarasawa'/561, l='MpServer', x=-463.70, y=7.00, z=-317.32]]
	Chunk stats: MultiplayerChunkCache: 289, 289
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-418,73,-149), Chunk: (at 14,4,11 in -27,-10; contains blocks -432,0,-160 to -417,255,-145), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 2757096 game time, 18000 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 38 total; [EntityEnderman['エンダーマン'/25867, l='MpServer', x=-469.51, y=66.00, z=-332.56], EntityEnderman['エンダーマン'/25871, l='MpServer', x=-464.47, y=66.00, z=-302.79], EntityEnderman['エンダーマン'/25891, l='MpServer', x=-442.08, y=66.00, z=-319.50], EntityEnderman['エンダーマン'/25894, l='MpServer', x=-442.50, y=66.00, z=-320.50], EntityPlayerSP['TakahiroKarasawa'/561, l='MpServer', x=-463.70, y=7.00, z=-317.32], EntityEnderman['エンダーマン'/25909, l='MpServer', x=-456.50, y=66.00, z=-290.50], EntityEnderman['エンダーマン'/25917, l='MpServer', x=-459.29, y=66.00, z=-305.65], EntityEnderman['エンダーマン'/25922, l='MpServer', x=-478.50, y=66.00, z=-305.50], EntityEnderman['エンダーマン'/25923, l='MpServer', x=-477.50, y=66.00, z=-305.16], EntityEnderman['エンダーマン'/25925, l='MpServer', x=-482.50, y=66.00, z=-302.50], EntityEnderman['エンダーマン'/25943, l='MpServer', x=-479.50, y=66.00, z=-309.50], EntityEnderman['エンダーマン'/25945, l='MpServer', x=-478.50, y=66.00, z=-305.50], EntityEnderman['エンダーマン'/25954, l='MpServer', x=-452.46, y=66.00, z=-317.48], EntityEnderman['エンダーマン'/25959, l='MpServer', x=-481.36, y=66.00, z=-310.35], EntityEnderman['エンダーマン'/25960, l='MpServer', x=-437.69, y=66.00, z=-326.70], EntityEnderman['エンダーマン'/25711, l='MpServer', x=-438.73, y=66.00, z=-302.76], EntityEnderman['エンダーマン'/25968, l='MpServer', x=-452.50, y=66.00, z=-338.50], EntityEnderman['エンダーマン'/25973, l='MpServer', x=-461.47, y=66.00, z=-305.62], EntityEnderman['エンダーマン'/25977, l='MpServer', x=-442.50, y=66.00, z=-327.50], EntityEnderman['エンダーマン'/25979, l='MpServer', x=-486.50, y=66.00, z=-304.50], EntityEnderman['エンダーマン'/25982, l='MpServer', x=-486.50, y=66.00, z=-303.50], EntityEnderman['エンダーマン'/25984, l='MpServer', x=-467.50, y=66.00, z=-303.50], EntityEnderman['エンダーマン'/25985, l='MpServer', x=-453.61, y=66.00, z=-292.53], EntityEnderman['エンダーマン'/25986, l='MpServer', x=-468.50, y=66.00, z=-295.50], EntityEnderman['エンダーマン'/25993, l='MpServer', x=-462.42, y=66.00, z=-311.52], EntityEnderman['エンダーマン'/25998, l='MpServer', x=-454.49, y=66.00, z=-329.61], EntityEnderman['エンダーマン'/26000, l='MpServer', x=-486.50, y=66.00, z=-320.50], EntityEnderman['エンダーマン'/26001, l='MpServer', x=-459.70, y=66.00, z=-292.54], EntityEnderman['エンダーマン'/26002, l='MpServer', x=-461.87, y=66.00, z=-292.08], EntityEnderman['エンダーマン'/25783, l='MpServer', x=-450.64, y=66.00, z=-310.35], EntityEnderman['エンダーマン'/26039, l='MpServer', x=-459.96, y=66.00, z=-313.11], EntityEnderman['エンダーマン'/26040, l='MpServer', x=-456.75, y=66.00, z=-313.77], EntityEnderman['エンダーマン'/26041, l='MpServer', x=-457.57, y=66.00, z=-312.05], EntityEnderman['エンダーマン'/26046, l='MpServer', x=-462.93, y=61.09, z=-325.08], EntityEnderman['エンダーマン'/25824, l='MpServer', x=-473.76, y=66.00, z=-293.46], EntityEnderman['エンダーマン'/25831, l='MpServer', x=-460.15, y=66.00, z=-305.10], EntityEnderman['エンダーマン'/25832, l='MpServer', x=-462.30, y=66.00, z=-305.84], EntityEnderman['エンダーマン'/25851, l='MpServer', x=-457.11, y=66.00, z=-324.08]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:529)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:400)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by Moobien** [comment]
@Epicsquid315 could this be a capabilities thing?

**Comment by EpicSquid** [comment]
First glance is making me think it's world corruption. Essentially the tile is being thought of as a conduit for some reason and that should not happen.

**Comment by modmuss50** [comment]
ill check that we are removing the tile from the world correctly but if that is ok then it could just be that world
