### ISSUE TITLE
Liquid Manager Seems to be broken

### ISSUE THREAD

**Issue by 666lumberjack** [TechReborn/StevesCarts#46]
Running StevesCarts-1.10.2-2.1.4.81, I can't get fluid to properly input into the liquid manager (some transfer methods will push to it, but nothing renders in the GUI and on mouseover all tanks appear empty) and the manager won't consistently input into a cart. I'm also having no luck inputting fluid to a cart or liquid manager via the GUI with buckets (this functionality seemed to work in the previous version, but the other issues mentioned existed there as well).

Let me know if I can provide any other useful info.

**Comment by twilightrazor** [comment]
I am running StevesCarts-1.11.2-2.3.0.22 and I am having this problem as well. It seems like Steve's Cart interactions with liquids are broken entirely as I cannot put lava into a internal tank manually.

**Comment by nightcipher** [comment]
Expected behavior: piping lava in to the Liquid Manager fills the internal tanks.

Actual behavior: game crashes upon lava trying to enter the Liquid Manager block.

My own crash report is below.

[crash-2017-07-20_02.07.57-server.txt](https://github.com/TechReborn/StevesCarts/files/1161318/crash-2017-07-20_02.07.57-server.txt)

**Comment by secondfry** [comment]
Just referencing error so it will be googlable:
```
Caused by: java.lang.ClassCastException: [Lvswe.stevescarts.helpers.storages.SCTank; cannot be cast to net.minecraftforge.fluids.capability.IFluidHandler
        at blusunrize.immersiveengineering.common.blocks.metal.TileEntityFluidPipe.getConnectionByte(TileEntityFluidPipe.java:409) ~[TileEntityFluidPipe.class:?]
        at blusunrize.immersiveengineering.common.blocks.metal.TileEntityFluidPipe.getAdvancedColisionBounds(TileEntityFluidPipe.java:500) ~[TileEntityFluidPipe.class:?]
        at blusunrize.immersiveengineering.common.blocks.BlockIETileProvider.func_185477_a(BlockIETileProvider.java:409) ~[BlockIETileProvider.class:?]
        at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185908_a(BlockStateContainer.java:451) ~[aws$a.class:?]
        at net.minecraft.world.World.func_191504_a(World.java:1332) ~[ams.class:?]
        at net.minecraft.world.World.func_184144_a(World.java:1357) ~[ams.class:?]
        at net.minecraft.entity.Entity.func_70091_d(Entity.java:720) ~[ve.class:?]
        at net.minecraft.entity.EntityLivingBase.func_191986_a(EntityLivingBase.java:1943) ~[vn.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_191986_a(EntityPlayer.java:1821) ~[aeb.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2377) ~[vn.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:511) ~[aeb.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2163) ~[vn.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:232) ~[aeb.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382) ~[oo.class:?]
        ... 9 more
```
Attaching IE pipe to Fluid manager corrupts world, mayday, mayday, server is down :D

**Comment by modmuss50** [comment]
This was fixed with the latest version

**Comment by oxinabox** [comment]
So [this commit? ](https://github.com/TechReborn/StevesCarts/commit/1d9336a27cb1a237790ead664e89d8fa6de6e3e1) ?

I take it it is not getting a backport to 1.11 ?
