### ISSUE TITLE
missing sounds

### ISSUE THREAD

**Issue by ternsip** [TechReborn/StevesCarts#66]
StevesCarts-1.10.2-2.1.4.83.jar
[10:17:43] [Client thread/WARN]: File minecraft:sounds/gearswitch.ogg does not exist, cannot add it to event stevescarts:gearswitch
[10:17:43] [Client thread/WARN]: File minecraft:sounds/win.ogg does not exist, cannot add it to event stevescarts:win
[10:17:43] [Client thread/WARN]: File minecraft:sounds/boop1.ogg does not exist, cannot add it to event stevescarts:boop
[10:17:43] [Client thread/WARN]: File minecraft:sounds/boop2.ogg does not exist, cannot add it to event stevescarts:boop
[10:17:43] [Client thread/WARN]: File minecraft:sounds/boop3.ogg does not exist, cannot add it to event stevescarts:boop
[10:17:43] [Client thread/WARN]: File minecraft:sounds/gameover.ogg does not exist, cannot add it to event stevescarts:gameover
[10:17:43] [Client thread/WARN]: File minecraft:sounds/1lines.ogg does not exist, cannot add it to event stevescarts:1lines
[10:17:43] [Client thread/WARN]: File minecraft:sounds/2lines.ogg does not exist, cannot add it to event stevescarts:2lines
[10:17:43] [Client thread/WARN]: File minecraft:sounds/3lines.ogg does not exist, cannot add it to event stevescarts:3lines
[10:17:43] [Client thread/WARN]: File minecraft:sounds/4lines.ogg does not exist, cannot add it to event stevescarts:4lines
[10:17:43] [Client thread/WARN]: File minecraft:sounds/highscore.ogg does not exist, cannot add it to event stevescarts:highscore
[10:17:43] [Client thread/WARN]: File minecraft:sounds/hit.ogg does not exist, cannot add it to event stevescarts:hit
[10:17:43] [Client thread/WARN]: File minecraft:sounds/click.ogg does not exist, cannot add it to event stevescarts:click
[10:17:43] [Client thread/WARN]: File minecraft:sounds/blobclick.ogg does not exist, cannot add it to event stevescarts:blobclick
[10:17:43] [Client thread/WARN]: File minecraft:sounds/flagclick.ogg does not exist, cannot add it to event stevescarts:flagclick
[10:17:43] [Client thread/WARN]: File minecraft:sounds/goodjob.ogg does not exist, cannot add it to event stevescarts:goodjob

**Comment by modmuss50** [comment]
I think most of them are to do with the arcade

**Comment by bookerthegeek** [comment]
## Heyo ##
I also am having this issue.
```
[08:43:25] [Client thread/WARN]: File minecraft:sounds/gearswitch.ogg does not exist, cannot add it to event stevescarts:gearswitch
[08:43:25] [Client thread/WARN]: File minecraft:sounds/win.ogg does not exist, cannot add it to event stevescarts:win
[08:43:25] [Client thread/WARN]: File minecraft:sounds/boop1.ogg does not exist, cannot add it to event stevescarts:boop
[08:43:25] [Client thread/WARN]: File minecraft:sounds/boop2.ogg does not exist, cannot add it to event stevescarts:boop
[08:43:25] [Client thread/WARN]: File minecraft:sounds/boop3.ogg does not exist, cannot add it to event stevescarts:boop
[08:43:25] [Client thread/WARN]: File minecraft:sounds/gameover.ogg does not exist, cannot add it to event stevescarts:gameover
[08:43:25] [Client thread/WARN]: File minecraft:sounds/1lines.ogg does not exist, cannot add it to event stevescarts:1lines
[08:43:25] [Client thread/WARN]: File minecraft:sounds/2lines.ogg does not exist, cannot add it to event stevescarts:2lines
[08:43:25] [Client thread/WARN]: File minecraft:sounds/3lines.ogg does not exist, cannot add it to event stevescarts:3lines
[08:43:25] [Client thread/WARN]: File minecraft:sounds/4lines.ogg does not exist, cannot add it to event stevescarts:4lines
[08:43:25] [Client thread/WARN]: File minecraft:sounds/highscore.ogg does not exist, cannot add it to event stevescarts:highscore
[08:43:25] [Client thread/WARN]: File minecraft:sounds/hit.ogg does not exist, cannot add it to event stevescarts:hit
[08:43:25] [Client thread/WARN]: File minecraft:sounds/click.ogg does not exist, cannot add it to event stevescarts:click
[08:43:25] [Client thread/WARN]: File minecraft:sounds/blobclick.ogg does not exist, cannot add it to event stevescarts:blobclick
[08:43:25] [Client thread/WARN]: File minecraft:sounds/flagclick.ogg does not exist, cannot add it to event stevescarts:flagclick
[08:43:25] [Client thread/WARN]: File minecraft:sounds/goodjob.ogg does not exist, cannot add it to event stevescarts:goodjob
[08:43:25] [Client thread/WARN]: Invalid sounds.json
java.lang.NullPointerException
	at net.minecraft.client.audio.SoundHandler.func_110549_a(SourceFile:82) [ccs.class:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:122) [cae.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:447) [bes.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:352) [bes.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_131]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_131]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:236) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:297) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:162) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:53) [NewLaunch.jar:?]
```
---
### Versions ###
- Forge-1.11.2-13.20.0.2366-universal.jar
- StevesCarts-1.11.2-2.3.0.22
